In [13]:
import torch
import train
import matplotlib.pyplot as plt
import numpy as np

# !python train.py

record = torch.load('train_result.pt')
record = np.array(record)

train_loss = record[:,0]
train_acc = record[:,1]
val_loss = record[:,2]
val_acc = record[:,3]
print(record.shape)
print(record)

plt.plot(range(record.shape[0]),train_loss,label='train_loss')
plt.plot(range(record.shape[0]),train_acc,label='train_acc')
plt.plot(range(record.shape[0]),val_loss, label='val_loss')
plt.plot(range(record.shape[0]),val_acc, label='val_acc')
plt.legend()
plt.show()

(1000, 4)
[[2.14698061e+00 1.36160714e-01 1.94522524e+00 2.69531250e-01]
 [1.74760830e+00 2.25446429e-01 1.66279101e+00 2.92534722e-01]
 [1.56338573e+00 2.89062500e-01 1.52048445e+00 3.00347222e-01]
 ...
 [3.34685610e-05 1.00000000e+00 3.79017911e-05 1.00000000e+00]
 [2.96771793e-05 1.00000000e+00 3.63647487e-05 1.00000000e+00]
 [2.80803971e-05 1.00000000e+00 3.48986214e-05 1.00000000e+00]]
